1. Problem Statement :
   - how much customers are going to churn
   - why they are churning 
   - how to reatain them
2. Get and Understand Dataset : head(), info(), describe()
3. clean data :
   - handle missing values
   - remove duplicates
   - correct errors and inconsistency
   - Standardize formats (dates, units, categories)
   - encoding
   - normalization (work on only numerical data)
4. EDA :
   - indentify pattern and outliers and visualize by graph
5. analyze/model :
   - analyze and build model 
6. Interpret results :
   - make outputs in meaningful insights
7. communication finding :
   - Present insights using:
       Dashboards
       Reports
       Presentations
8. Make Decisions & Take Action :

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset= pd.read_csv('Bank_churn.csv')
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

# 1. Understanding Data

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10002 non-null  int64
 1   CustomerId       10002 non-null  int64
 2   Surname          10002 non-null  object
 3   CreditScore      10002 non-null  int64
 4   Geography        10001 non-null  object
 5   Gender           10002 non-null  object
 6   Age              10001 non-null  float64
 7   Tenure           10002 non-null  int64
 8   Balance          10002 non-null  float64
 9   NumOfProducts    10002 non-null  int64
 10  HasCrCard        10001 non-null  float64
 11  IsActiveMember   10001 non-null  float64
 12  EstimatedSalary  10002 non-null  float64
 13  Exited           10002 non-null  int64
dtypes: float64(5), int64(6), object(3)
memory usage: 1.1+ MB

In [4]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10002.000000,1.000200e+04,10002.000000,10001.000000,10002.000000,10002.000000,10002.000000,10001.000000,10001.000000,10002.000000,10002.000000
mean,5001.499600,1.569093e+07,650.555089,38.922311,5.012498,76491.112875,1.530194,0.705529,0.514949,100083.331145,0.203759
std,2887.472338,7.193177e+04,96.661615,10.487200,2.891973,62393.474144,0.581639,0.455827,0.499801,57508.117802,0.402812
min,1.000000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,2501.250000,1.562852e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.000000,0.000000,50983.750000,0.000000
50%,5001.500000,1.569073e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.000000,1.000000,100185.240000,0.000000
75%,7501.750000,1.575323e+07,718.000000,44.000000,7.000000,127647.840000,2.000000,1.000000,1.000000,149383.652500,0.000000
max,10000.000000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [5]:
df= dataset.copy()
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [6]:
df= df.sort_values(by='CustomerId', ascending=True).reset_index(drop=True)
df['RowNumber']= df.index

In [7]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15565701,Ferri,698,Spain,Female,39.0,9,161993.89,1,0.0,0.0,90212.38,0
1,1,15565706,Akobundu,612,Spain,Male,35.0,1,0.00,1,1.0,1.0,83256.26,1
2,2,15565714,Cattaneo,601,France,Male,47.0,1,64430.06,2,0.0,1.0,96517.97,0
3,3,15565779,Kent,627,Germany,Female,30.0,6,57809.32,1,1.0,0.0,188258.49,0
4,4,15565796,Docherty,745,Germany,Male,48.0,10,96048.55,1,1.0,0.0,74510.65,0

In [8]:
df.columns= df.columns.str.lower()

In [9]:
df.head()

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,0,15565701,Ferri,698,Spain,Female,39.0,9,161993.89,1,0.0,0.0,90212.38,0
1,1,15565706,Akobundu,612,Spain,Male,35.0,1,0.00,1,1.0,1.0,83256.26,1
2,2,15565714,Cattaneo,601,France,Male,47.0,1,64430.06,2,0.0,1.0,96517.97,0
3,3,15565779,Kent,627,Germany,Female,30.0,6,57809.32,1,1.0,0.0,188258.49,0
4,4,15565796,Docherty,745,Germany,Male,48.0,10,96048.55,1,1.0,0.0,74510.65,0

# 2. Handling missing values

In [10]:
df.isnull().sum()

rownumber          0
customerid         0
surname            0
creditscore        0
geography          1
gender             0
age                1
tenure             0
balance            0
numofproducts      0
hascrcard          1
isactivemember     1
estimatedsalary    0
exited             0
dtype: int64

In [11]:
df['geography']= df['geography'].fillna(df['geography'].mode()[0])
df['age'] = df['age'].fillna(df['age'].mode()[0])
df['hascrcard']= df['hascrcard'].fillna(df['hascrcard'].mode()[0])
df['isactivemember']= df['isactivemember'].fillna(df['isactivemember'].mode()[0])
df['gender']= df['gender'].fillna(df['gender'].mode()[0])

In [12]:
df.isnull().sum()

rownumber          0
customerid         0
surname            0
creditscore        0
geography          0
gender             0
age                0
tenure             0
balance            0
numofproducts      0
hascrcard          0
isactivemember     0
estimatedsalary    0
exited             0
dtype: int64

# 3. Handling Duplicates

In [13]:
df[df.duplicated(subset=["customerid", 'balance'], keep=False)]  # both CustomerId and balance is same

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
2497,2497,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
2498,2498,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
4657,4657,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
4658,4658,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1

In [14]:
df=df.drop_duplicates(subset=["customerid", 'balance'], keep='first')

In [15]:
df[df.duplicated(subset=["customerid", 'balance'], keep=False)]  # both CustomerId and balance is same

Empty DataFrame
Columns: [rownumber, customerid, surname, creditscore, geography, gender, age, tenure, balance, numofproducts, hascrcard, isactivemember, estimatedsalary, exited]
Index: []

# 4. Extracting Features

In [16]:
dft= df.drop(['rownumber', 'customerid', 'surname'], axis=1)
dft.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,698,Spain,Female,39.0,9,161993.89,1,0.0,0.0,90212.38,0
1,612,Spain,Male,35.0,1,0.00,1,1.0,1.0,83256.26,1
2,601,France,Male,47.0,1,64430.06,2,0.0,1.0,96517.97,0
3,627,Germany,Female,30.0,6,57809.32,1,1.0,0.0,188258.49,0
4,745,Germany,Male,48.0,10,96048.55,1,1.0,0.0,74510.65,0

In [17]:
dft['exited'].value_counts()

exited
0    7963
1    2037
Name: count, dtype: int64

In [18]:
dft.duplicated().sum()

np.int64(0)

In [19]:
dft["hascrcard"] = dft["hascrcard"].replace(
    {"Yes": 1, "No": 0, "Y": 1, "N": 0, "yes": 1, "no": 0, "y": 1, "n": 0}
).astype(int)

# 5. One Hot Encoding

In [20]:
dft.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,698,Spain,Female,39.0,9,161993.89,1,0,0.0,90212.38,0
1,612,Spain,Male,35.0,1,0.00,1,1,1.0,83256.26,1
2,601,France,Male,47.0,1,64430.06,2,0,1.0,96517.97,0
3,627,Germany,Female,30.0,6,57809.32,1,1,0.0,188258.49,0
4,745,Germany,Male,48.0,10,96048.55,1,1,0.0,74510.65,0

In [21]:
print(dft['geography'].value_counts())
print(dft['gender'].value_counts())

geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64
gender
Male      5457
Female    4543
Name: count, dtype: int64

I) Encoding using pandas

In [22]:
dft['gender'] = pd.Categorical(
    dft['gender'],
    categories=['Female', 'Male', 'Other']
)

In [23]:
dft['gender'].value_counts()

gender
Male      5457
Female    4543
Other        0
Name: count, dtype: int64

In [24]:
enc= pd.get_dummies(data=dft, columns=['gender'], drop_first=True, dtype=int)  # drop categorical col 1st instead in alphabetical order
dft=enc

In [25]:
dft.head()

,creditscore,geography,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,gender_Male,gender_Other
0,698,Spain,39.0,9,161993.89,1,0,0.0,90212.38,0,0,0
1,612,Spain,35.0,1,0.00,1,1,1.0,83256.26,1,1,0
2,601,France,47.0,1,64430.06,2,0,1.0,96517.97,0,1,0
3,627,Germany,30.0,6,57809.32,1,1,0.0,188258.49,0,0,0
4,745,Germany,48.0,10,96048.55,1,1,0.0,74510.65,0,1,0

In [26]:
dft['geography'].value_counts()

geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [27]:
enc2= pd.get_dummies(data=dft, columns=['geography'], drop_first=True, dtype=int)
dft=enc2

In [28]:

dft.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,gender_Male,gender_Other,geography_Germany,geography_Spain
0,698,39.0,9,161993.89,1,0,0.0,90212.38,0,0,0,0,1
1,612,35.0,1,0.00,1,1,1.0,83256.26,1,1,0,0,1
2,601,47.0,1,64430.06,2,0,1.0,96517.97,0,1,0,0,0
3,627,30.0,6,57809.32,1,1,0.0,188258.49,0,0,0,1,0
4,745,48.0,10,96048.55,1,1,0.0,74510.65,0,1,0,1,0

II) Encoding using sklearn

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
"""
encoder2= OneHotEncoder(drop='first', sparse_output=False)
encoded_array = encoder2.fit_transform(dft[['gender']])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder2.get_feature_names_out(['gender'])
)
encoded_df
"""

"\nencoder2= OneHotEncoder(drop='first', sparse_output=False)\nencoded_array = encoder2.fit_transform(dft[['gender']])\n\nencoded_df = pd.DataFrame(\n    encoded_array,\n    columns=encoder2.get_feature_names_out(['gender'])\n)\nencoded_df\n"

# 6. train test split

In [31]:
X= dft.drop(columns=['exited'])
y= dft[['exited']]

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
X_train.shape, X_test.shape

((8000, 12), (2000, 12))

In [35]:
y_train.shape, y_test.shape

((8000, 1), (2000, 1))

# 7. Outliers Handling

In [36]:
X_train.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,gender_Male,gender_Other,geography_Germany,geography_Spain
9256,658,39.0,7,0.00,2,1,0.0,48378.40,1,0,0,0
1561,681,58.0,8,93173.88,1,1,1.0,139761.25,0,0,0,0
1670,760,43.0,6,175735.50,1,1,1.0,157337.29,1,0,0,1
6089,477,47.0,9,144900.58,1,1,0.0,61315.37,1,0,0,0
6671,727,71.0,8,0.00,1,1,1.0,198446.91,1,0,0,1

In [37]:
X_train.describe()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,gender_Male,gender_Other,geography_Germany,geography_Spain
count,8000.000000,8000.000000,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.0,8000.000000,8000.000000
mean,649.844250,39.017379,5.03375,76365.972586,1.533250,0.707125,0.514125,99975.288954,0.543875,0.0,0.250375,0.247500
std,96.573779,10.545264,2.89295,62498.226356,0.580893,0.455110,0.499832,57575.822405,0.498102,0.0,0.433256,0.431587
min,350.000000,18.000000,0.00000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000,0.0,0.000000,0.000000
25%,583.000000,32.000000,3.00000,0.000000,1.000000,0.000000,0.000000,50488.107500,0.000000,0.0,0.000000,0.000000
50%,652.000000,37.000000,5.00000,97245.995000,1.000000,1.000000,1.000000,100218.210000,1.000000,0.0,0.000000,0.000000
75%,717.000000,44.000000,8.00000,127644.240000,2.000000,1.000000,1.000000,149190.167500,1.000000,0.0,1.000000,0.000000
max,850.000000,92.000000,10.00000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000,0.0,1.000000,1.000000

In [38]:
(X_train['balance'] > 215000.090000).sum()

np.int64(4)

In [39]:
(X_train['balance'] > 10000.09).sum()

np.int64(5095)

1. For Balance

In [40]:
q3bal= X_train['balance'].quantile(0.75)
q1bal= X_train['balance'].quantile(0.25)
IQR1= q3bal-q1bal
print('q3=',q3bal, '\n', 'q1=', q1bal, '\n', 'IQR=', IQR1)

q3= 127644.24
 q1= 0.0
 IQR= 127644.24

In [41]:
lower1= q1bal- 1.5* IQR1
upper1= q3bal+ 1.5* IQR1

In [42]:
lower1, upper1

(np.float64(-191466.36000000002), np.float64(319110.60000000003))

In [43]:
outliers_balance = X_train[
    (X_train['balance'] < lower1) |
    (X_train['balance'] > upper1)
]

In [44]:
outliers_balance

Empty DataFrame
Columns: [creditscore, age, tenure, balance, numofproducts, hascrcard, isactivemember, estimatedsalary, gender_Male, gender_Other, geography_Germany, geography_Spain]
Index: []

In [45]:
outliers_balance.shape[0]

0

In [46]:
X_train = X_train[
    (X_train['balance'] >= lower1) &
    (X_train['balance'] <= upper1)
]

In [47]:
X_train.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,gender_Male,gender_Other,geography_Germany,geography_Spain
9256,658,39.0,7,0.00,2,1,0.0,48378.40,1,0,0,0
1561,681,58.0,8,93173.88,1,1,1.0,139761.25,0,0,0,0
1670,760,43.0,6,175735.50,1,1,1.0,157337.29,1,0,0,1
6089,477,47.0,9,144900.58,1,1,0.0,61315.37,1,0,0,0
6671,727,71.0,8,0.00,1,1,1.0,198446.91,1,0,0,1

2. For Tensure

In [48]:
q3ten= X_train['tenure'].quantile(0.75)
q1ten= X_train['tenure'].quantile(0.25)
IQR2= q3ten-q1ten
print('q3=',q3ten, '\n', 'q1=', q1ten, '\n', 'IQR=', IQR2)

q3= 8.0
 q1= 3.0
 IQR= 5.0

In [49]:
lower2= q1ten- 1.5* IQR2
upper2= q3ten+ 1.5* IQR2
lower2, upper2

(np.float64(-4.5), np.float64(15.5))

In [50]:
outliers_tenure = X_train[
    (X_train['tenure'] < lower2) |
    (X_train['tenure'] > upper2)
]

In [51]:
outliers_tenure

Empty DataFrame
Columns: [creditscore, age, tenure, balance, numofproducts, hascrcard, isactivemember, estimatedsalary, gender_Male, gender_Other, geography_Germany, geography_Spain]
Index: []

In [52]:
outliers_tenure.shape[0]

0

In [53]:
X_train = X_train[
    (X_train['tenure'] >= lower2) &
    (X_train['tenure'] <= upper2)
]

In [54]:
X_train.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,gender_Male,gender_Other,geography_Germany,geography_Spain
9256,658,39.0,7,0.00,2,1,0.0,48378.40,1,0,0,0
1561,681,58.0,8,93173.88,1,1,1.0,139761.25,0,0,0,0
1670,760,43.0,6,175735.50,1,1,1.0,157337.29,1,0,0,1
6089,477,47.0,9,144900.58,1,1,0.0,61315.37,1,0,0,0
6671,727,71.0,8,0.00,1,1,1.0,198446.91,1,0,0,1

In [55]:
X_train.shape

(8000, 12)

3. Estimated Salary

In [56]:
q3est= X_train['estimatedsalary'].quantile(0.75)
q1est= X_train['estimatedsalary'].quantile(0.25)
IQR3= q3est-q1est
print('q3=',q3est, '\n', 'q1=', q1est, '\n', 'IQR=', IQR3)

q3= 149190.1675
 q1= 50488.1075
 IQR= 98702.06000000001

In [57]:
lower3= q1est- 1.5* IQR3
upper3= q3est+ 1.5* IQR3
lower3, upper3

(np.float64(-97564.98250000003), np.float64(297243.25750000007))

In [58]:
outliers_est_sal = X_train[
    (X_train['estimatedsalary'] < lower3) |
    (X_train['estimatedsalary'] > upper3)
]

In [59]:
outliers_est_sal

Empty DataFrame
Columns: [creditscore, age, tenure, balance, numofproducts, hascrcard, isactivemember, estimatedsalary, gender_Male, gender_Other, geography_Germany, geography_Spain]
Index: []

In [60]:
outliers_tenure.shape[0]

0

In [61]:
X_train = X_train[
    (X_train['estimatedsalary'] >= lower3) &
    (X_train['estimatedsalary'] <= upper3)
]

In [62]:
X_train.shape

(8000, 12)

In [63]:
X_train= X_train[X_train['age'] >=18 ]

In [64]:
X_train.shape

(8000, 12)

# 8. Standardization / Normalization

NameError: name 'handle_outliers' is not defined

In [71]:
from sklearn.preprocessing import StandardScaler

num_cols = [
    'creditscore',
    'age',
    'tenure',
    'balance',
    'numofproducts',
    'estimatedsalary'
]

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols]) # not scale data 
# on fit data its create its own statistics mean, standard deviation and transform according to that
# hence we do not use fit transform with test which differ mean, deviation from train data

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [69]:
X_train.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

# Analyzing Dataset

In [ ]:
(df[df['exited'] == 1]).shape

In [ ]:
df[(df['balance'] == 0)].shape

In [ ]:
(df[(df['balance'] == 0) & (df['exited'] == 1)]).shape

In [ ]:
(df[(df['balance'] == 0) & (df['exited'] == 0)]).shape

In [ ]:
# (df[(df['balance'] == 0) & (df['exited'] == 1)] & (df['balance'] == 0)).shape

In [ ]:
(df[(df['age'] > 70) & (df['exited'] == 1)]).shape

In [ ]:
(df[df['age'] > 70]).shape

In [ ]:
df.describe()

In [ ]:
plt.figure(figsize=(15,15))
sns.heatmap(dft.corr(), cmap='coolwarm', annot=True)

In [ ]:
dft.corr()

In [ ]:
"""
Most Exiting Peoples Due To :
1. in germany
2. balance
3. age
"""

In [ ]:
plt.figure(figsize=(6,4))
sns.boxplot(x='exited', y='balance', data=df)
plt.title('Balance vs Exited')
plt.xlabel('Exited')
plt.ylabel('Balance')
plt.show()

In [ ]:
(df[(df['balance'] >= 80000) & (df['balance'] <= 120000) & (df['exited'] == 1)]).shape

In [ ]:
(df[(df['balance'] >= 80000) & (df['balance'] <= 120000) & (df['exited'] == 0)]).shape

In [ ]:
plt.figure(figsize=(6,4))
sns.boxplot(x='exited', y='age', data=df)
plt.title('age vs Exited')
plt.xlabel('Exited')
plt.ylabel('age')
plt.show()

In [ ]:
(df[(df['age'] >= 35) & (df['age'] <= 45) & (df['exited'] == 0)]).shape

In [ ]:
(df[(df['age'] >= 35) & (df['age'] <= 45) & (df['exited'] == 1)]).shape

In [ ]:
# (df['exited'] == 1).sum()  =>  2037

In [ ]:
(df[(df['age'] >= 35) & (df['age'] <= 45) & (df['balance'] >= 80000) & (df['balance'] <= 120000) & (df['exited'] == 1)]).shape

In [ ]:
(df[(df['age'] >= 35) & (df['age'] <= 45) & (df['balance'] >= 90000) & (df['balance'] <= 120000) & (df['exited'] == 0)]).shape

In [ ]:
plt.figure(figsize=(6,4))
sns.boxplot(x='exited', y='geography_Germany', data=dft)
plt.title('geography_Germany vs Exited')
plt.xlabel('Exited')
plt.ylabel('geography_Germany')
plt.show()

In [ ]:
(dft[(dft['age'] >= 35) & (dft['age'] <= 45) & (dft['balance'] >= 80000) & (dft['balance'] <= 120000) & (dft['geography_Germany'] == 1) & (dft['exited'] == 1)]).shape

In [ ]:
(dft[(dft['age'] >= 35) & (dft['age'] <= 45) & (dft['balance'] >= 80000) & (dft['balance'] <= 120000) & (dft['geography_Germany'] == 0) & (dft['exited'] == 1)]).shape

In [ ]:
(dft[dft['geography_Germany'] == 1]).shape

In [ ]:
(dft[(dft['geography_Germany'] >= 1) & (dft['exited'] == 0)]).shape

# 9. Training Model

1. Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42
)

model_rf.fit(X_train, y_train)

In [ ]:
print("Train accuracy:", model_rf.score(X_train, y_train))
print("Test accuracy:", model_rf.score(X_test, y_test))

In [ ]:
from sklearn.svm import LinearSVC

# Faster SVM for large datasets
model_svm = LinearSVC(
    C=1,
    random_state=42,
    max_iter=5000
)

model_svm.fit(X_train, y_train)

In [ ]:
model_svm.score(X_train, y_train)

In [ ]:
model_svm.score(X_test, y_test)

In [ ]:
from xgboost import XGBClassifier
model_xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
model_xgb.fit(X_train, y_train)

In [ ]:
# =========================================
# Compare Gym Models & Select Best Model
# =========================================

models = {
    "SVM": model_svm,
    "Random Forest": model_rf,
    "XGBoost": model_xgb
}

best_model_name = None
best_model = None
best_score = 0

print("\n===== GYM MODEL COMPARISON =====\n")

for name, model in models.items():

    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    print(f"{name}")
    print(f"Training Accuracy : {train_score:.4f}")
    print(f"Testing Accuracy  : {test_score:.4f}")
    print("-" * 35)

    # Select Model With Highest Test Accuracy
    if test_score > best_score:
        best_score = test_score
        best_model_name = name
        best_model = model

# =========================================
# Final Best Model
# =========================================

print(f"\nBest Model Selected : {best_model_name}")
print(f"Best Accuracy : {best_score:.4f}")

In [ ]:
new_customer = pd.DataFrame(0, index=[0], columns=X.columns)

In [ ]:
new_customer['creditscore'] = 720
new_customer['age'] = 35
new_customer['tenure'] = 5
new_customer['balance'] = 85000
new_customer['numofproducts'] = 2
new_customer['hascrcard'] = 1
new_customer['isactivemember'] = 1
new_customer['estimatedsalary'] = 650

In [ ]:
new_customer['gender_Male'] = 1

new_customer['geography_Spain'] = 1

In [ ]:
new_customer_scaled = scaler.transform(new_customer)

# Convert Back To DataFrame
new_customer_scaled = pd.DataFrame(
    new_customer_scaled,
    columns=X.columns
)

In [ ]:
df.head(3)

In [ ]:
dft.head()

In [ ]:
X_train.head()